spring.application.name=demo

spring.datasource.url=jdbc:postgresql://localhost:5432/postgres_sber
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# Схема из pg_dump — Hibernate не создаёт/не меняет таблицы. Для проверки маппинга можно поставить validate
spring.jpa.hibernate.ddl-auto=none
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.jdbc.time_zone=UTC
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

